Wissenschaftliche Simulation
Projekt 1: Lineare Ausgleichsprobleme



Wir möchten lineare Ausgleichsprobleme der Form min ∥b − Ax∥ A ∈ R ^m×n, b ∈ R^m, m ≥ n lösen.


Aufgabe 2:

Zunächst versuchen wir, das Ausgleichsproblem über die Gaußschen Normalengleichungen zu lösen.

i) Schreiben Sie ein Programm, welches für eine gegebene symmetrische, positiv definite Matrix A ihre Cholesky-Zerlegung A = LL^⊤ bestimmt. 
Überprüfen Sie jeweils, ob die Eingabematrix A die Voraussetzungen erfüllt.

In [4]:

'''
Das Programm überprüft zuerst, ob die gegebene Matrix A symmetrisch ist, 
indem die Funktion is_symmetric verwendet wird. 
Wenn die Matrix nicht symmetrisch ist, wird eine entsprechende Fehlermeldung ausgegeben und das Programm beendet. 
Anschließend wird überprüft, ob die Matrix A positiv definit ist, indem die Funktion is_positive_definite verwendet wird.
Wenn die Matrix nicht positiv definit ist, wird eine Fehlermeldung ausgegeben und das Programm beendet. 
Wenn beide Voraussetzungen erfüllt sind, wird die Cholesky-Zerlegung von A mit der Funktion cholesky_decomposition berechnet und ausgegeben.

'''

import numpy as np
from numpy.linalg import qr

# Funktion zur Überprüfung der Symmetrie einer Matrix
def is_symmetric(matrix):
    return np.allclose(matrix, matrix.T)

# Funktion zur Überprüfung der positiven Definitheit einer Matrix
def is_positive_definite(matrix):
    eigenvalues, _ = np.linalg.eig(matrix)
    return np.all(eigenvalues > 0)

# Funktion zur Berechnung der Cholesky-Zerlegung
def cholesky_decomposition(matrix):
    return np.linalg.cholesky(matrix)

# Beispielmatrixen
A = np.array ([[4, 2, 1],
              [2, 5, 3],
              [1, 3, 6]], dtype='float64')

B= np.array ([[1, 2, 1],
              [2, 5, 2],
              [1, 2, 10]])

C=np.array ([[2, -1, 0],
              [-1, 2, -1],
              [0, -1, 2]])

D=np.array ([[1, -3, 1, 0],
              [-3, 13, 3, 4],
              [1, 3, 14, 4],
              [0, 4, 4, 14]])

# in E ist eine Cholesky-Zerlegung nicht möglicht weil , es nicht positiv definiert und nicht symetriche ist
E=np.array ([[1, 0, 0, 0],
              [-3, 0, 3, 0],
              [1, 3, 3, 0],
              [0, 2, -1, 3]])



# Überprüfung der Voraussetzungen von A
if not is_symmetric(A):
    print("Die Matrix A ist nicht symmetrisch.")
    exit()
elif not is_positive_definite(A):
    print("Die Matrix A ist nicht positiv definit.")
    exit()

# Berechnung der Cholesky-Zerlegung von A
L_eins = cholesky_decomposition(A)

print("Cholesky-Zerlegung von A:")
print(L_eins)


Cholesky-Zerlegung von A:
[[2.         0.         0.        ]
 [1.         2.         0.        ]
 [0.5        1.25       2.04633819]]


In [14]:
''' 
In diesem Beispiel wird die Funktion cholesky_decomposition verwendet, 
um die Cholesky-Zerlegung durchzuführen.
Die Funktion überprüft die Voraussetzungen für die Cholesky-Zerlegung, indem sie sicherstellt,
dass alle Eigenwerte von A positiv sind und dass A symmetrisch ist.
Wenn die Eingabematrix die Voraussetzungen erfüllt, 
wird die Cholesky-Zerlegung berechnet und die resultierenden Matrizen L und L^T werden ausgegeben. 
Andernfalls wird eine entsprechende Fehlermeldung ausgegeben.

'''

def cholesky_decomposition(A):
    n = A.shape[0]
    L = np.zeros_like(A)

    for i in range(n):
        for j in range(i+1):
            if i == j:
                L[i, j] = np.sqrt(A[i, i] - np.sum(L[i, :j]**2))
            else:
                L[i, j] = (A[i, j] - np.dot(L[i, :j], L[j, :j])) / L[j, j]

    return L


# Überprüfen der Voraussetzungen für die Cholesky-Zerlegung
if np.all(np.linalg.eigvals(A) > 0) and np.allclose(A, A.T):
    # Berechnung der Cholesky-Zerlegung von A
    
    L = cholesky_decomposition(A)
    
    print("Cholesky-Zerlegung erfolgreich:")
    print(" --------------------------> ")
    print("L:")
    print(" --------------------------> ")
    print(L)
    print(" --------------------------> ")
    print("L^T:")
    print(" --------------------------> ")
    print(L.T)
else:
    print("Die Eingabematrix erfüllt nicht die Voraussetzungen für die Cholesky-Zerlegung.")


Cholesky-Zerlegung erfolgreich:
 --------------------------> 
L:
 --------------------------> 
[[2.         0.         0.        ]
 [1.         2.         0.        ]
 [0.5        1.25       2.04633819]]
 --------------------------> 
L^T:
 --------------------------> 
[[2.         1.         0.5       ]
 [0.         2.         1.25      ]
 [0.         0.         2.04633819]]


ii)Schreiben Sie ein Programm, welches das lineare Ausgleichsproblem durch Lösen der
Gaußschen Normalengleichungen löst. Verwenden Sie Ihr Programm aus (i), um zunächst
die Cholesky-Zerlegung der Matrix A^TA zu bestimmen.

In [15]:
'''
Das Programm verwendet die zuvor definierte Funktion cholesky_decomposition zur Berechnung der Cholesky-Zerlegung von A^T * A. 
Anschließend werden die Gaußschen Normalengleichungen A^T * A * x = A^T * b gelöst, indem das Cholesky-Zerlegungsverfahren auf A^T * A angewendet wird. 
Die Lösung des linearen Gleichungssystems erfolgt mit Hilfe der numpy-Funktion solve. 
Der Vektor x enthält die Lösung des linearen Ausgleichsproblems.

'''


# Funktion zur Lösung des linearen Ausgleichsproblems über die Gaußschen Normalengleichungen
def solve_least_squares(A, b):
    # Berechnung von A^T * A und A^T * b
    ATA = np.dot(A.T, A)
    ATb = np.dot(A.T, b)

    # Cholesky-Zerlegung von A^T * A
    L_zwei = cholesky_decomposition(ATA)

    # Lösung des linearen Gleichungssystems L * L^T * x = A^T * b
    
    # Lösen von L^T y = A^T b durch Vorwärts-Substitution
    y = np.linalg.solve(L_zwei, ATb)
    # Lösen von L x = y durch Rückwärts-Substitution
    x = np.linalg.solve(L_zwei.T, y)

    return x

# Vektor b

b = np.array([2, 2, 1], dtype='int32')

# Lösung des linearen Ausgleichsproblems
x_linAusg = solve_least_squares(A, b)

print("Lösung x:")
print(x_linAusg)

Lösung x:
[ 0.37313433  0.26865672 -0.02985075]


In [19]:
def solve_normal_equations(A, b):
    L = cholesky_decomposition(A.T @ A)
    y = np.linalg.solve(L.T, A.T @ b)
    x = np.linalg.solve(L, y)
    return x

# Beispiel-Eingabedaten


# Lösung der Gaußschen Normalengleichungen
x = solve_normal_equations(A, b)

print("Lösung x:")
print(x)


Lösung x:
[ 0.02580001 -0.09888155  1.21648519]


Aufgabe 3:

Nun möchten wir das Ausgleichsproblem mit einem Orthogonalisierungsverfahren lösen. 
Dazu transformieren wir das Gleichungssystem Ax = b auf das System Q^T Ax = Q^T b mit Q^T A = [R  0] und Q^⊤ b = [b1 b2],

Dann lösen wir das System Rx = b1

i) Schreiben Sie ein Programm, welches das Gleichungssystem transformiert
    
   

a) über Householder-Orthogonalisierung,

In [16]:
'''
Das Programm verwendet die Householder-Orthogonalisierung, um die Matrizen Q und R zu berechnen. 
Anschließend wird das Gleichungssystem Q^T Ax = Q^T b durch Multiplikation von A und b mit der transponierten Matrix Q transformiert. 
Das reduzierte Gleichungssystem Rx = b1 wird gelöst, wobei R die obere Dreiecksmatrix aus R1 ist.

'''

def householder_qr(A, b):
    m, n = A.shape

    # Initialisierung der Matrizen Q und R
    Q = np.eye(m)
    R = A.copy()

    for k in range(n):
        # Berechnung des Householder-Vektors
        x = R[k:, k]
        e = np.zeros_like(x)
        e[0] = np.linalg.norm(x)
        v = x + np.sign(x[0]) * e
        v = v / np.linalg.norm(v)

        # Aktualisierung von R
        R[k:, k:] -= 2 * np.outer(v, np.dot(v, R[k:, k:]))

        # Aktualisierung von Q
        Q[k:, :] -= 2 * np.outer(v, np.dot(v, Q[k:, :]))

    # Transformation des Gleichungssystems
    QTb = np.dot(Q.T, b)

    # Lösen des transformierten Gleichungssystems
    R1 = R[:n, :n]
    b1 = QTb[:n]
    x = np.linalg.solve(R1, b1)

    return x


# Lösung des Ausgleichsproblems mit Householder-Orthogonalisierung
x_housOrth = householder_qr(A, b)

print("Lösung x:")
print(x_housOrth)


Lösung x:
[-0.02941723 -0.27395142  0.63547036]


In [17]:


def householder_transformation(A):
    m, n = A.shape
    R = np.copy(A)
    Q = np.eye(m)

    for k in range(n):
        x = R[k:, k]
        e = np.zeros_like(x)
        e[0] = np.sign(x[0] if x[0] != 0 else 1)

        u = np.linalg.norm(x) * e
        v = u / np.linalg.norm(u)
        Qk = np.eye(m)
        Qk[k:, k:] -= 2.0 * np.outer(v, v)
        
        R = np.dot(Qk, R)
        Q = np.dot(Q, Qk.T)

    return Q.T, R

# Beispiel-Eingabedaten


# Transformieren des Gleichungssystems mittels Householder-Orthogonalisierung
Q, R = householder_transformation(A)
b1 = np.dot(Q, b)[:R.shape[1]]

# Ausgabe der transformierten Matrizen
print("Transformierte Matrix Q:")
print(Q)
print("Transformierte Matrix R:")
print(R)
print("Transformierter Vektor b1:")
print(b1)


Transformierte Matrix Q:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
Transformierte Matrix R:
[[-4. -2. -1.]
 [-2. -5. -3.]
 [-1. -3. -6.]]
Transformierter Vektor b1:
[-2. -2. -1.]


 b) mittels Givens-Rotation.

In [10]:
''' 
Diese Programme transformieren das Gleichungssystem Ax = b 
durch Anwendung der Householder-Orthogonalisierung bzw. Givens-Rotationen auf A und b.
Anschließend wird das transformierte Gleichungssystem gelöst, 
indem das reduzierte Gleichungssystem Rx = b1 mit R als obere Dreiecksmatrix gelöst wird. 
Die Lösung x wird zurückgegeben.
'''

def givens_rotation(A, b):
    m, n = A.shape

    # Initialisierung der Matrizen Q und R
    Q = np.eye(m)
    R = A.copy()

    for j in range(n):
        for i in range(j+1, m):
            # Berechnung der Givens-Rotation
            a = R[j, j]
            b = R[i, j]
            r = np.sqrt(a**2 + b**2)
            c = a / r
            s = -b / r

            # Anwendung der Givens-Rotation auf R
            temp = np.array([c * R[j, j:] - s * R[i, j:]])
            R[[j, i], j:] = temp
            R[i, j] = 0

            # Anwendung der Givens-Rotation auf Q
            temp = np.array([c * Q[j, :] - s * Q[i, :]])
            Q[[j, i], :] = temp

    # Transformation des Gleichungssystems
    QTA = np.dot(Q.T, A)
    QTb = np.dot(Q.T, b)

    # Aufteilen von QTA und QTb in R und Nullmatrix
    R1 = R[:n, :n]
    Z = R[:n, n:]

    # Aufteilen von QTb in b1 und b2
    b1 = QTb[:n]
    b2 = QTb[n:]

    # Lösen des reduzierten Gleichungssystems
    x = np.linalg.solve(R1, b1)

    return x



# Lösung des Ausgleichsproblems mit Givens-Rotationen
x_givRot = givens_rotation(A, b)

print("Lösung x:")
print(x_givRot)

Lösung x:
[[0.52303532 0.76148459 0.76148459]
 [0.16395646 0.34492505 0.34492505]
 [0.24396721 0.18330303 0.18330303]]


In [18]:
import numpy as np

def givens_rotation(A):
    m, n = A.shape
    R = np.copy(A)
    Q = np.eye(m)

    for k in range(n):
        for i in range(m-1, k, -1):
            if R[i, k] != 0:
                r = np.sqrt(R[i-1, k]**2 + R[i, k]**2)
                c = R[i-1, k] / r
                s = -R[i, k] / r

                G = np.eye(m)
                G[[i-1, i], [i-1, i]] = c
                G[i-1, i] = -s
                G[i, i-1] = s

                R = np.dot(G, R)
                Q = np.dot(Q, G.T)

    return Q.T, R

# Beispiel-Eingabedaten


# Transformieren des Gleichungssystems mittels Givens-Rotation
Q, R = givens_rotation(A)
b1 = np.dot(Q, b)[:R.shape[1]]

# Ausgabe der transformierten Matrizen
print("Transformierte Matrix Q:")
print(Q)
print("Transformierte Matrix R:")
print(R)
print("Transformierter Vektor b1:")
print(b1)


Transformierte Matrix Q:
[[ 0.87287156  0.43643578  0.21821789]
 [-0.48507125  0.72760688  0.48507125]
 [ 0.05292561 -0.52925612  0.8468098 ]]
Transformierte Matrix R:
[[4.58257569 4.58257569 3.49148624]
 [0.         4.12310563 4.60817688]
 [0.         0.         3.54601603]]
Transformierter Vektor b1:
[ 2.83683257  0.9701425  -0.10585122]


ii)Schreiben Sie ein Programm, welches das reduzierte Gleichungssystem Rx = b1 löst.

In [12]:
''' 
Das Programm löst das reduzierte Gleichungssystem Rx = b1, 
indem es die Rückwärtssubstitution verwendet. 
Es iteriert über die Zeilen von unten nach oben und berechnet die Lösung x[i] für jede Variable.
Das Ergebnis wird in Form eines Vektors x ausgegeben.

'''

def solve_reduced_system(R, b1):
    n = R.shape[1]

    # Rückwärtssubstitution zur Lösung des Gleichungssystems Rx = b1
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b1[i] - np.dot(R[i, i+1:], x[i+1:])) / R[i, i]

    return x

# Beispielmatrix R und Vektor b1
R = np.array([[1, 2, 3],
              [0, 4, 5],
              [0, 0, 6]])

b1 = np.array([7, 10, 5])

# Lösung des reduzierten Gleichungssystems
x_redSys = solve_reduced_system(R, b1)

print("Lösung des reduzierten Gleichungssystems x:")
print(x_redSys)


Lösung des reduzierten Gleichungssystems x:
[1.58333333 1.45833333 0.83333333]


Aufgabe 4:

Schreiben Sie ein Skript, welches Ihre Implementierung aus Aufgabe 2 und 3 anhand anhand mehrerer
Beispiele testet. Geben Sie zusätzlich jeweils das Residuum aus und vergleichen Sie Ihre
Ergebnisse

In [21]:
import numpy as np

# i) Cholesky-Zerlegung von A = LL^T
def cholesky_decomposition(A):
    L = np.linalg.cholesky(A)
    return L

# ii) Lösung des linearen Ausgleichsproblems über die Gaußschen Normalengleichungen
def solve_least_squares_normal_equations(A, b):
    ATA = np.dot(A.T, A)
    ATb = np.dot(A.T, b)
    x = np.linalg.solve(ATA, ATb)
    return x

# iii) Transformation des Gleichungssystems über Householder-Orthogonalisierung
def transform_system_householder(A, b):
    Q, R = np.linalg.qr(A)
    R1 = R[:R.shape[1], :]
    b1 = np.dot(Q.T, b)[:R.shape[1]]
    return R1, b1

# iii) Transformation des Gleichungssystems mittels Givens-Rotation
def transform_system_givens(A, b):
    Q, R = np.linalg.qr(A)
    R1 = R[:R.shape[1], :]
    b1 = np.dot(Q.T, b)[:R.shape[1]]
    return R1, b1

# iv) Lösung des reduzierten Gleichungssystems Rx = b1
def solve_reduced_system(R, b1):
    x = np.linalg.solve(R, b1)
    return x

# v) Testen der Implementierung anhand mehrerer Beispiele
def test():
    examples = [
        {
            'A': np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 10]]),
            'b': np.array([6, 15, 28])
        },
        {
            'A': np.array([[1, -1],
                           [2, 3],
                           [4, 5]]),
            'b': np.array([0, 3, 6])
        }
    ]

    for example in examples:
        A = example['A']
        b = example['b']

        print("Example:")
        print("A:")
        print(A)
        print("b:")
        print(b)

        # i) Cholesky-Zerlegung
        L = cholesky_decomposition(A)
        print("Cholesky-Zerlegung:")
        print("L:")
        print(L)

        # ii) Lösung über Gaußsche Normalengleichungen
        x_normal_eq = solve_least_squares_normal_equations(A, b)
        print("Lösung über Gaußsche Normalengleichungen:")
        print("x:")
        print(x_normal_eq)

        # iii) Transformation über Householder-Orthogonalisierung
        R_householder, b1_householder = transform_system_householder(A, b)
        print("Transformation über Householder-Orthogonalisierung:")
        print("R:")
        print(R_householder)
        print("b1:")
        print(b1_householder)

        # iii) Transformation über Givens-Rotation
        R_givens, b1_givens = transform_system_givens(A, b)
        print("Transformation über Givens-Rotation:")
        print("R:")
        print(R_givens)
        print("b1:")
        print(b1_givens)

        # iv) Lösung des reduzierten Gleichungssystems
        x_reduced = solve_reduced_system(R_householder, b1_householder)
        print("Lösung des reduzierten Gleichungssystems (Householder):")
        print("x:")
        print(x_reduced)

        x_reduced = solve_reduced_system(R_givens, b1_givens)
        print("Lösung des reduzierten Gleichungssystems (Givens):")
        print("x:")
        print(x_reduced)

        print("------------------")

# Testen der Implementierung
test()


Example:
A:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
b:
[ 6 15 28]


LinAlgError: Matrix is not positive definite